version: "2"
services:
  topic-extract:
    container_name: topic-extract
    build:
      context: app/
      dockerfile: deployment/prod/Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./models:/app/models
      - ./data:/app/data
    restart: always